version: '{build}'

image: Visual Studio 2013

#environment:
#  APPVEYOR_RDP_PASSWORD: 'FooBar01!'

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  global:
    python_exe: C:\Python36-x64\python.exe
  matrix:
    - appveyor_driver_target_os: Win7
    - appveyor_driver_target_os: Win8
    - appveyor_driver_target_os: Win8.1

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

  # On Win32, only build Debug to speed things up:
  exclude:
    - platform: Win32
      configuration: Release

install:
  - git submodule update --init --recursive

build_script:
  - cd um\cmake
  - '"%python_exe%" -m project.ci.cmake --install'
  - cd ..\..
  - ps: .\.appveyor\build.ps1 -InstallDir ..\build\install

after_build:
  - 7z.exe a "%APPVEYOR_PROJECT_NAME%-%PLATFORM%-%CONFIGURATION%-%appveyor_driver_target_os%.zip" "..\build\install\*"
  - appveyor.exe PushArtifact "%APPVEYOR_PROJECT_NAME%-%PLATFORM%-%CONFIGURATION%-%appveyor_driver_target_os%.zip"

for:
# Build Release on master only to speed things up:
- branches:
    except:
      - master
  configuration:
    - Debug

# Workers are 64-bit, can't load 32-bit drivers.
# https://github.com/appveyor/ci/issues/715
- matrix:
    only:
      - platform: x64
  install:
    - git submodule update --init --recursive
    - appveyor.exe AddMessage "Enabling self-signed drivers..."
    - bcdedit.exe /set TESTSIGNING ON
    - appveyor.exe AddMessage "Rebooting the worker..."
    - ps: Restart-Computer -Force
    - ps: Start-Sleep -s 10
    - appveyor.exe AddMessage "OK"
  test_script:
    - ps: .\.appveyor\test.ps1 -InstallDir ..\build\install
